update dependencies
Build failed on nightly rust due to:

error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /Users/xxchan/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-be2141875385cea5/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |